# Generated by Django 3.2.7 on 2022-10-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=32, unique=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('type', models.IntegerField()),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
